hello:
  msg: Hello World
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/DB_NAME
    password: SHOULD_BE_YOUR_DB_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
